//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.03 at 01:00:44 AM MSK 
//


package com.example.ingredient;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ingredientType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ingredientType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="water" type="{http://www.example.com/ingredient}ingredientValueWaterType" />
 *       &lt;attribute name="sugar" type="{http://www.example.com/ingredient}ingredientValueType" />
 *       &lt;attribute name="fructose" type="{http://www.example.com/ingredient}ingredientValueType" />
 *       &lt;attribute name="choco-type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="MILK"/>
 *             &lt;enumeration value="DARK"/>
 *             &lt;enumeration value="WHITE"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="vanillin" type="{http://www.example.com/ingredient}ingredientValueType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ingredientType")
public class IngredientType {

    @XmlAttribute(name = "water")
    protected String water;
    @XmlAttribute(name = "sugar")
    protected Integer sugar;
    @XmlAttribute(name = "fructose")
    protected Integer fructose;
    @XmlAttribute(name = "choco-type")
    protected String chocoType;
    @XmlAttribute(name = "vanillin")
    protected Integer vanillin;

    /**
     * Gets the value of the water property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWater() {
        return water;
    }

    /**
     * Sets the value of the water property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWater(String value) {
        this.water = value;
    }

    /**
     * Gets the value of the sugar property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSugar() {
        return sugar;
    }

    /**
     * Sets the value of the sugar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSugar(Integer value) {
        this.sugar = value;
    }

    /**
     * Gets the value of the fructose property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFructose() {
        return fructose;
    }

    /**
     * Sets the value of the fructose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFructose(Integer value) {
        this.fructose = value;
    }

    /**
     * Gets the value of the chocoType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChocoType() {
        return chocoType;
    }

    /**
     * Sets the value of the chocoType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChocoType(String value) {
        this.chocoType = value;
    }

    /**
     * Gets the value of the vanillin property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVanillin() {
        return vanillin;
    }

    /**
     * Sets the value of the vanillin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVanillin(Integer value) {
        this.vanillin = value;
    }

}
